"""fix field name

Revision ID: 3e15760fc33d
Revises: 283d7864df39
Create Date: 2025-12-10 12:53:59.334500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e15760fc33d'
down_revision: Union[str, Sequence[str], None] = '283d7864df39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=False))
    op.drop_column('users', 'refresg_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresg_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
